FROM python:3.11-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1 
# Prevents Python from writing .pyc files to disk
ENV PYTHONUNBUFFERED 1

# setting up the working directory
WORKDIR /app
# Copy the requirements file into the container
COPY requirements.txt /app/

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire project into the container
COPY . /app/

WORKDIR /app/challenges_platform


# Expose the port the app runs on
EXPOSE 8000

# Run the Django development server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]